### ISSUE TITLE
code isn't loaded?

### ISSUE THREAD

**Issue by fourteentrees** [Eris9/Dankmemer#1]
i have had this error twice

how do i fix this? this is what i get when i start the bot:
![image](https://user-images.githubusercontent.com/37120379/127955819-25427a0a-715f-4cb0-b0a0-cae69663c9cb.png)

**Comment by wynwxst** [comment]
Im not quite sure about that yet

**Comment by wynwxst** [comment]
are you using linux?

**Comment by wynwxst** [comment]
With a further look at this, I will be posting an update and be updating the wiki, and will then explain what to do here

**Comment by fourteentrees** [comment]
Hi there, I'm using Windows 10 22000 (technically Win11 lol)...I don't know if it doesn't work with Windows (would be weird because you have build docs for it).

**Comment by fourteentrees** [comment]
Oh wow I'm a stupid idiot, the fix you posted in the wiki worked. Thank you so much!

**Comment by wynwxst** [comment]
Before i close this, the issue was due to not putting the path and rethinkdb
