### ISSUE TITLE
Prefix issue

### ISSUE THREAD

**Issue by Devilop12** [Eris9/Dankmemer#2]
Bot is online but what is prefix where to set it. Am on replit

**Comment by wynwxst** [comment]
`src/config.json`

**Comment by wynwxst** [comment]
@Devilop12

**Comment by Devilop12** [comment]
Still not working

**Comment by fourteentrees** [comment]
I do not recommend replit. Run it off your own computer, maybe?

even better, get Linode or some generic VPS provider. GCP, AWS, Azure to name a few.

**Comment by wynwxst** [comment]
@Devilop12 could you describe further?

**Comment by wynwxst** [comment]
> I do not recommend replit. Run it off your own computer, maybe?
> 
> even better, get Linode or some generic VPS provider. GCP, AWS, Azure to name a few.

Heroku is fairly stable so it should be a good stopgap while they try to attain a better form of hosting.

**Comment by Devilop12** [comment]
Which app to use?

**Comment by wynwxst** [comment]
@Devilop12 try and find a stable discord bot hosting service using google or if you're good enough with your terminal try using [this](https://elements.heroku.com/buildpacks/synicalsyntax/discord.js-heroku).

**Comment by fourteentrees** [comment]
> > I do not recommend replit. Run it off your own computer, maybe?
> > even better, get Linode or some generic VPS provider. GCP, AWS, Azure to name a few.
> 
> Heroku is fairly stable so it should be a good stopgap while they try to attain a better form of hosting.

yes, exactly. they don't offer persistent storage but that shouldn't be an issue.

**Comment by wynwxst** [comment]
Closing due to no further inquiries
