### ISSUE TITLE
fix the item system

### ISSUE THREAD

**Issue by fourteentrees** [Eris9/Dankmemer#3]
Hey it's me again. Shop is disabled for some reason.

I am willing to contribute to re-enabling it but since Node is not my language of choice the fix will be just the quickest, dirtiest one I can think of.

**Comment by fourteentrees** [comment]
Right now I'm looking for commits from other repos so if you wanna help just reply!

**Comment by wynwxst** [comment]
> Right now I'm looking for commits from other repos so if you wanna help just reply!



> Hey it's me again. Shop is disabled for some reason.
> 
> I am willing to contribute to re-enabling it but since Node is not my language of choice the fix will be just the quickest, dirtiest one I can think of.

I'll examine the issue

**Comment by wynwxst** [comment]
```nodejs
const { GenericCommand } = require('../../models/')
module.exports = new GenericCommand(
  async ({ Memer, msg, addCD }) => {
    return 'The shop will be available in an update coming very soon... Better save your coins!'
  },
  {
    triggers: ['shop'],
    cooldown: 1000,
    donorBlocked: true,
    description: 'Shop for some dank items and upgrades!'
  }
)
```
Either try turning donorBlocked to false or set yourself as donor but it will just send ''The shop will be available in an update coming very soon... Better save your coins!''
As mentioned before this is an older version and not the latest version.

**Comment by fourteentrees** [comment]
> ```
> const { GenericCommand } = require('../../models/')
> module.exports = new GenericCommand(
>   async ({ Memer, msg, addCD }) => {
>     return 'The shop will be available in an update coming very soon... Better save your coins!'
>   },
>   {
>     triggers: ['shop'],
>     cooldown: 1000,
>     donorBlocked: true,
>     description: 'Shop for some dank items and upgrades!'
>   }
> )
> ```
> 
> Either try turning donorBlocked to false or set yourself as donor but it will just send ''The shop will be available in an update coming very soon... Better save your coins!'' As mentioned before this is an older version and not the latest version.

i'll see what I can do to fix this - Closing for now
