### ISSUE TITLE
prefix

### ISSUE THREAD

**Issue by fartabomination** [Eris9/Dankmemer#6]
Prefix has been set but the bot does not reply.

![image](https://github.com/wynwxst/Dankmemer/assets/115855298/e82d179a-566d-4336-9df5-e4e941c8935e)

![image](https://github.com/wynwxst/Dankmemer/assets/115855298/00afa79f-5d49-4f63-b786-6f284a9360a9)

**Comment by fartabomination** [comment]
Was in dev mode. In config.json set it to false in order to make it work

**Comment by wynwxst** [comment]
> Was in dev mode. In config.json set it to false in order to make it work

Apologies for not replying sooner, I was busy. I'm glad you found out why, let me know if there's any other way I can help

**Comment by fartabomination** [comment]
> > Was in dev mode. In config.json set it to false in order to make it work
> 
> Apologies for not replying sooner, I was busy. I'm glad you found out why, let me know if there's any other way I can help

You don't also happen to know how to get rid of the default items in the inventory or add to it? Or should I just open a new issue?

**Comment by fartabomination** [comment]
> > > Was in dev mode. In config.json set it to false in order to make it work
> > 
> > 
> > Apologies for not replying sooner, I was busy. I'm glad you found out why, let me know if there's any other way I can help
> 
> You don't also happen to know how to get rid of the default items in the inventory or add to it? Or should I just open a new issue?

Never mind I found it lol

**Comment by wynwxst** [comment]
> > > Was in dev mode. In config.json set it to false in order to make it work
> > 
> > 
> > Apologies for not replying sooner, I was busy. I'm glad you found out why, let me know if there's any other way I can help
> 
> You don't also happen to know how to get rid of the default items in the inventory or add to it? Or should I just open a new issue?

From what I remember, dank memer stores their data using rethinkdb and redis. You can manipulate and edit this data to insert inventory items
